### ISSUE TITLE
Question: how to "logout"?

### ISSUE THREAD

**Issue by Tony2** [pinepain/ldap-auth-proxy#22]
sorry if this is not the right place to ask for support.

After a successful login, how can a user logout? By "logout" I mean the user will be asked to enter credentials to browse the protected site. One solution is to clear browser cookie, but it's not that user-friendly.

**Comment by pinepain** [comment]
Hi, the logout is kinda tricky, as the http basic auth doesn't really have "lougout" mechanism afair.

The ldap auth proxy is just an authentication method on the backend to check credentials. It is used with the [HTTP Auth](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) framework using Basic scheme and thus same restrictions (including security) applies. 

I would suggest to search for how to log out using http basic auth, e.g. [this result](https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication) and [this one](https://superuser.com/questions/917602/how-do-i-log-out-with-http-basic) from stackoverflow&co might give you better perspective on how to deal with it. Also, relevant RFC is always nice to check. 

I would say that basic auth is rarely a good option these days, and this project was made in quite a hurry at the time when I needed something quick, the task at that time was to expose some internal docs to a 3rd-party vendor we were partnering, so that was not mission critical information in that scenario, so the basic auth did the job. Hope it will gives you a brief understanding of the problem and applicable use cases. I still have it in my backlog to redo basic auth on sth more sustainable, but so far so good, it's still there, lol.

**Comment by Tony2** [comment]
thank you for the nice reply, I find it very informative and helpful.
